[project]
name = "data-ingestion"
version = "0.2.0"
description = "Ingestion Pipeline for Kafka Events"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chromadb>=1.1.1",
    "llama-index>=0.14.4",
    "llama-index-embeddings-ollama>=0.8.3",
    "llama-index-embeddings-openai>=0.3.3",
    "llama-index-llms-ollama>=0.8.0",
    "llama-index-llms-openai>=0.3.3",
    "llama-index-vector-stores-chroma>=0.5.3",
    "pandas>=2.0.0",
    "pydantic>=2.0.0",
    "openpyxl>=3.0.0",
    "streamlit>=1.50.0",
    "kafka-python>=2.2.15",
    "fastapi[standard]>=0.120.1",
    "uvicorn>=0.37.0",
    "aiokafka>=0.12.0",
    "alembic>=1.17.1",
    "tenacity>=9.1.2",
    "mysql-connector-python>=9.5.0",
    "pymysql>=1.1.2",
    "aiomysql>=0.3.2",
    "cryptography>=46.0.3",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.0.0",
    "pytest-asyncio>=0.23.0",
]

[dependency-groups]
dev = [
    "ipykernel>=7.0.1",
]
