"""Init Migration

Revision ID: 8bbea2c02605
Revises: 
Create Date: 2025-11-05 13:48:50.339294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bbea2c02605'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query', sa.String(length=512), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('entity', sa.Enum('company', 'product', name='entity'), nullable=False),
    sa.Column('reaction', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('action_by', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=1024), nullable=True),
    sa.CheckConstraint('reaction IN (0, 1)', name='check_reaction_binary'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('query', 'document_id', 'entity', 'tenant_id', name='uix_query_document_entity_tenant')
    )
    op.create_index(op.f('ix_feedback_document_id'), 'feedback', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_document_id'), table_name='feedback')
    op.drop_table('feedback')
    # ### end Alembic commands ###
