"""add tenant and tenant_plan models

Revision ID: b5de869b78be
Revises: 8bbea2c02605
Create Date: 2025-11-06 17:06:44.320926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5de869b78be'
down_revision: Union[str, Sequence[str], None] = '8bbea2c02605'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('tenant_name', sa.String(length=255), nullable=False),
    sa.Column('secret_key_primary', sa.String(length=512), nullable=False),
    sa.Column('secret_key_secondary', sa.String(length=512), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('onboarding_status', sa.Enum('pending', 'active', 'failed', 'suspended', name='onboardingstatus'), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id'),
    sa.UniqueConstraint('tenant_name')
    )
    op.create_index('ix_tenants_onboarding_status', 'tenants', ['onboarding_status'], unique=False)
    op.create_table('tenant_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('plan_name', sa.String(length=255), nullable=False),
    sa.Column('plan_type', sa.Enum('predefined', 'custom', name='plantype'), server_default='predefined', nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('priority', sa.Integer(), server_default='0', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tenant_plans_dates', 'tenant_plans', ['start_date', 'end_date'], unique=False)
    op.create_index('ix_tenant_plans_priority', 'tenant_plans', ['priority'], unique=False)
    op.create_index('ix_tenant_plans_tenant_active', 'tenant_plans', ['tenant_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_tenant_plans_tenant_id'), 'tenant_plans', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenant_plans_tenant_id'), table_name='tenant_plans')
    op.drop_index('ix_tenant_plans_tenant_active', table_name='tenant_plans')
    op.drop_index('ix_tenant_plans_priority', table_name='tenant_plans')
    op.drop_index('ix_tenant_plans_dates', table_name='tenant_plans')
    op.drop_table('tenant_plans')
    op.drop_index('ix_tenants_onboarding_status', table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
